const COMMON = 5;
const RARE = 3.75;
const EPIC = 2.5;
const LEGENDARY = 1.25;
const HERO = 0;

const cards: Cards = {
  26000065: {
    name: "mightyMiner",
    cost: 4,
    rarity: HERO,
    dsName: "MightyMiner",
  },
  26000028: {
    name: "threeMusketeers",
    cost: 9,
    rarity: RARE,
    dsName: "3M",
  },
  26000038: {
    name: "iceGolem",
    cost: 2,
    rarity: RARE,
    dsName: "IceGolem",
  },
  26000044: {
    name: "hunter",
    cost: 4,
    rarity: EPIC,
    dsName: "Hunter",
  },
  26000050: {
    name: "royalGhost",
    cost: 3,
    rarity: LEGENDARY,
    dsName: "Ghost",
  },
  26000059: {
    name: "royalHogs",
    cost: 5,
    rarity: RARE,
    dsName: "RoyalHogs",
  },
  26000074: {
    name: "goldenKnight",
    cost: 4,
    rarity: HERO,
    dsName: "GoldenKnight",
  },
  28000015: {
    name: "barbBarrel",
    cost: 2,
    rarity: EPIC,
    dsName: "BarbBarrel",
  },
  28000016: {
    name: "healSpirit",
    cost: 1,
    rarity: RARE,
    dsName: "HealSpirit",
  },
  26000009: {
    name: "golem",
    cost: 8,
    rarity: EPIC,
    dsName: "Golem",
  },
  26000013: {
    name: "bomber",
    cost: 2,
    rarity: COMMON,
    dsName: "Bomber",
  },
  26000016: {
    name: "prince",
    cost: 5,
    rarity: EPIC,
    dsName: "Prince",
  },
  26000048: {
    name: "nightWitch",
    cost: 4,
    rarity: LEGENDARY,
    dsName: "NightWitch",
  },
  26000049: {
    name: "bats",
    cost: 2,
    rarity: COMMON,
    dsName: "Bats",
  },
  26000080: {
    name: "skeletonDragons",
    cost: 4,
    rarity: COMMON,
    dsName: "SkeletonDragons",
  },
  28000007: {
    name: "lightning",
    cost: 6,
    rarity: EPIC,
    dsName: "Lightning",
  },
  28000012: {
    name: "tornado",
    cost: 3,
    rarity: EPIC,
    dsName: "Tornado",
  },
  26000010: {
    name: "skeletons",
    cost: 1,
    rarity: COMMON,
    dsName: "Skellies",
  },
  26000027: {
    name: "darkPrince",
    cost: 4,
    rarity: EPIC,
    dsName: "DarkPrince",
  },
  26000072: {
    name: "archerQueen",
    cost: 5,
    rarity: HERO,
    dsName: "ArcherQueen",
  },
  26000083: {
    name: "motherWitch",
    cost: 4,
    rarity: LEGENDARY,
    dsName: "MotherWitch",
  },
  26000085: {
    name: "electroGiant",
    cost: 8,
    rarity: EPIC,
    dsName: "ElectroGiant",
  },
  27000012: {
    name: "goblinCage",
    cost: 4,
    rarity: RARE,
    dsName: "GoblinCage",
  },
  26000047: {
    name: "royalRecruits",
    cost: 7,
    rarity: COMMON,
    dsName: "RoyalRecruits",
  },
  26000052: {
    name: "zappies",
    cost: 4,
    rarity: RARE,
    dsName: "Zappies",
  },
  26000057: {
    name: "flyingMachine",
    cost: 4,
    rarity: RARE,
    dsName: "FlyingMachine",
  },
  28000000: {
    name: "fireball",
    cost: 4,
    rarity: RARE,
    dsName: "Fireball",
  },
  28000001: {
    name: "arrows",
    cost: 3,
    rarity: COMMON,
    dsName: "Arrows",
  },
  26000004: {
    name: "pekka",
    cost: 7,
    rarity: EPIC,
    dsName: "PEKKA",
  },
  26000006: {
    name: "balloon",
    cost: 5,
    rarity: EPIC,
    dsName: "Balloon",
  },
  26000015: {
    name: "babyDragon",
    cost: 4,
    rarity: EPIC,
    dsName: "BabyD",
  },
  26000035: {
    name: "lumberjack",
    cost: 4,
    rarity: LEGENDARY,
    dsName: "Lumber",
  },
  26000042: {
    name: "electroWizard",
    cost: 4,
    rarity: LEGENDARY,
    dsName: "eWiz",
  },
  28000005: {
    name: "freeze",
    cost: 4,
    rarity: EPIC,
    dsName: "Freeze",
  },
  28000008: {
    name: "zap",
    cost: 2,
    rarity: COMMON,
    dsName: "Zap",
  },
  26000008: {
    name: "barbarians",
    cost: 5,
    rarity: COMMON,
    dsName: "Barbs",
  },
  26000029: {
    name: "lavaHound",
    cost: 7,
    rarity: LEGENDARY,
    dsName: "Lava",
  },
  26000032: {
    name: "miner",
    cost: 3,
    rarity: LEGENDARY,
    dsName: "Miner",
  },
  26000037: {
    name: "infernoDragon",
    cost: 4,
    rarity: LEGENDARY,
    dsName: "InfernoD",
  },
  26000046: {
    name: "bandit",
    cost: 3,
    rarity: LEGENDARY,
    dsName: "Bandit",
  },
  26000051: {
    name: "ramRider",
    cost: 5,
    rarity: LEGENDARY,
    dsName: "RamRider",
  },
  26000055: {
    name: "megaKnight",
    cost: 7,
    rarity: LEGENDARY,
    dsName: "MegaKnight",
  },
  26000084: {
    name: "electroSpirit",
    cost: 1,
    rarity: COMMON,
    dsName: "ElectroSpirit",
  },
  26000012: {
    name: "skeletonArmy",
    cost: 3,
    rarity: EPIC,
    dsName: "Skarmy",
  },
  26000024: {
    name: "royalGiant",
    cost: 6,
    rarity: COMMON,
    dsName: "RG",
  },
  26000026: {
    name: "princess",
    cost: 3,
    rarity: LEGENDARY,
    dsName: "Princess",
  },
  26000040: {
    name: "dartGoblin",
    cost: 3,
    rarity: RARE,
    dsName: "DartGob",
  },
  28000004: {
    name: "goblinBarrel",
    cost: 3,
    rarity: EPIC,
    dsName: "Barrel",
  },
  26000033: {
    name: "sparky",
    cost: 6,
    rarity: LEGENDARY,
    dsName: "Sparky",
  },
  26000043: {
    name: "eliteBarbarians",
    cost: 6,
    rarity: COMMON,
    dsName: "eBarbs",
  },
  26000060: {
    name: "goblinGiant",
    cost: 6,
    rarity: EPIC,
    dsName: "GobGiant",
  },
  28000002: {
    name: "rage",
    cost: 2,
    rarity: EPIC,
    dsName: "Rage",
  },
  26000000: {
    name: "knight",
    cost: 3,
    rarity: COMMON,
    dsName: "Knight",
  },
  26000017: {
    name: "wizard",
    cost: 5,
    rarity: RARE,
    dsName: "Wiz",
  },
  26000020: {
    name: "giantSkeleton",
    cost: 6,
    rarity: EPIC,
    dsName: "GiantSkelly",
  },
  26000021: {
    name: "hog",
    cost: 4,
    rarity: RARE,
    dsName: "Hog",
  },
  28000011: {
    name: "log",
    cost: 2,
    rarity: LEGENDARY,
    dsName: "Log",
  },
  26000003: {
    name: "giant",
    cost: 5,
    rarity: RARE,
    dsName: "Giant",
  },
  26000005: {
    name: "minions",
    cost: 3,
    rarity: COMMON,
    dsName: "Minions",
  },
  26000007: {
    name: "witch",
    cost: 5,
    rarity: EPIC,
    dsName: "Witch",
  },
  28000010: {
    name: "graveyard",
    cost: 5,
    rarity: LEGENDARY,
    dsName: "Graveyard",
  },
  28000017: {
    name: "snowball",
    cost: 2,
    rarity: COMMON,
    dsName: "Snowball",
  },
  26000034: {
    name: "bowler",
    cost: 5,
    rarity: EPIC,
    dsName: "Bowler",
  },
  26000063: {
    name: "electroDragon",
    cost: 5,
    rarity: EPIC,
    dsName: "eDragon",
  },
  26000002: {
    name: "goblins",
    cost: 2,
    rarity: COMMON,
    dsName: "Gobs",
  },
  26000011: {
    name: "valkyrie",
    cost: 4,
    rarity: RARE,
    dsName: "Valk",
  },
  26000030: {
    name: "iceSpirit",
    cost: 1,
    rarity: COMMON,
    dsName: "IceSpirit",
  },
  26000045: {
    name: "executioner",
    cost: 5,
    rarity: EPIC,
    dsName: "Exe",
  },
  28000003: {
    name: "rocket",
    cost: 6,
    rarity: RARE,
    dsName: "Rocket",
  },
  26000054: {
    name: "cannonCart",
    cost: 5,
    rarity: COMMON,
    dsName: "CannonCart",
  },
  27000001: {
    name: "goblinHut",
    cost: 5,
    rarity: RARE,
    dsName: "GobHut",
  },
  27000010: {
    name: "furnace",
    cost: 4,
    rarity: RARE,
    dsName: "Furnace",
  },
  26000019: {
    name: "spearGoblins",
    cost: 2,
    rarity: COMMON,
    dsName: "SpearGobs",
  },
  26000022: {
    name: "minionHorde",
    cost: 5,
    rarity: COMMON,
    dsName: "Horde",
  },
  26000041: {
    name: "goblinGang",
    cost: 3,
    rarity: COMMON,
    dsName: "GobGang",
  },
  27000002: {
    name: "mortar",
    cost: 4,
    rarity: COMMON,
    dsName: "Mortar",
  },
  26000053: {
    name: "rascals",
    cost: 5,
    rarity: COMMON,
    dsName: "Rascals",
  },
  28000006: {
    name: "mirror",
    cost: 1.5,
    rarity: EPIC,
    dsName: "Mirror",
  },
  26000069: {
    name: "skeletonKing",
    cost: 4,
    rarity: HERO,
    dsName: "SkeletonKing",
  },
  26000058: {
    name: "wallbreakers",
    cost: 2,
    rarity: EPIC,
    dsName: "WallBreakers",
  },
  26000062: {
    name: "magicArcher",
    cost: 4,
    rarity: LEGENDARY,
    dsName: "MagicArcher",
  },
  27000004: {
    name: "bombTower",
    cost: 4,
    rarity: RARE,
    dsName: "BombTower",
  },
  26000014: {
    name: "musketeer",
    cost: 4,
    rarity: RARE,
    dsName: "Musk",
  },
  28000009: {
    name: "poison",
    cost: 4,
    rarity: EPIC,
    dsName: "Poison",
  },
  26000018: {
    name: "miniPekka",
    cost: 4,
    rarity: RARE,
    dsName: "MP",
  },
  26000031: {
    name: "fireSpirit",
    cost: 1,
    rarity: COMMON,
    dsName: "FireSpirit",
  },
  26000036: {
    name: "battleRam",
    cost: 4,
    rarity: RARE,
    dsName: "Ram",
  },
  26000067: {
    name: "elixirGolem",
    cost: 3,
    rarity: RARE,
    dsName: "ElixirGolem",
  },
  26000068: {
    name: "battleHealer",
    cost: 4,
    rarity: RARE,
    dsName: "BattleHealer",
  },
  26000023: {
    name: "iceWizard",
    cost: 3,
    rarity: LEGENDARY,
    dsName: "IceWiz",
  },
  27000006: {
    name: "tesla",
    cost: 4,
    rarity: LEGENDARY,
    dsName: "Tesla",
  },
  27000008: {
    name: "xbow",
    cost: 6,
    rarity: EPIC,
    dsName: "XBow",
  },
  26000039: {
    name: "megaMinion",
    cost: 3,
    rarity: RARE,
    dsName: "MM",
  },
  26000061: {
    name: "fisherman",
    cost: 3,
    rarity: COMMON,
    dsName: "Fisherman",
  },
  26000025: {
    name: "guards",
    cost: 3,
    rarity: EPIC,
    dsName: "Guards",
  },
  27000013: {
    name: "goblinDrill",
    cost: 3,
    rarity: EPIC,
    dsName: "GoblinDrill",
  },
  26000056: {
    name: "skeletonBarrel",
    cost: 3,
    rarity: COMMON,
    dsName: "SkellyBarrel",
  },
  26000064: {
    name: "firecracker",
    cost: 3,
    rarity: COMMON,
    dsName: "Firecracker",
  },
  27000005: {
    name: "barbarianHut",
    cost: 7,
    rarity: RARE,
    dsName: "BarbHut",
  },
  27000007: {
    name: "elixirCollector",
    cost: 6,
    rarity: RARE,
    dsName: "Pump",
  },
  27000000: {
    name: "cannon",
    cost: 3,
    rarity: COMMON,
    dsName: "Cannon",
  },
  27000009: {
    name: "tombstone",
    cost: 3,
    rarity: RARE,
    dsName: "Tombstone",
  },
  27000003: {
    name: "infernoTower",
    cost: 5,
    rarity: RARE,
    dsName: "Inferno",
  },
  26000001: {
    name: "archer",
    cost: 3,
    rarity: COMMON,
    dsName: "Archers",
  },
  28000013: {
    name: "clone",
    cost: 3,
    rarity: EPIC,
    dsName: "Clone",
  },
  28000014: {
    name: "earthquake",
    cost: 3,
    rarity: RARE,
    dsName: "Earthquake",
  },
  28000018: {
    name: "royalDelivery",
    cost: 3,
    rarity: COMMON,
    dsName: "RoyalDelivery",
  },
};
